use crate::{SecurityCategory, SecurityLevel};

#[derive(Debug, Clone, Copy)]
/// A model asset declared in the static download manifest.
pub struct AssetSpec {
    /// Scanner category that owns this asset.
    pub category: SecurityCategory,
    /// Minimum security level that needs this asset.
    pub level: SecurityLevel,
    /// Hugging Face repository identifier.
    pub repo: &'static str,
    /// File path inside the Hugging Face repository.
    pub source_path: &'static str,
    /// Relative path below the category cache directory.
    pub destination_path: &'static str,
    /// Whether missing or failed downloads should block `warmup`.
    pub required: bool,
}

pub const ASSET_MANIFEST: &[AssetSpec] = &[
    // Prompt injection: L1 is native Rust. L2 keeps the existing cascade assets.
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "cascade/cascade_config.json",
        destination_path: "cascade_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/model_A.txt",
        destination_path: "model_A.txt",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/model_B.txt",
        destination_path: "model_B.txt",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/model_C.txt",
        destination_path: "model_C.txt",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/tfidf_word_A.json",
        destination_path: "tfidf_word_A.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/tfidf_char_A.json",
        destination_path: "tfidf_char_A.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/tfidf_word_B.json",
        destination_path: "tfidf_word_B.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/tfidf_char_B.json",
        destination_path: "tfidf_char_B.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/tfidf_word_C.json",
        destination_path: "tfidf_word_C.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/tfidf_char_C.json",
        destination_path: "tfidf_char_C.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/logistic_regression_C.json",
        destination_path: "logistic_regression_C.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L2,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "l2/fasttext_C.json",
        destination_path: "fasttext_C.json",
        required: true,
    },
    // Wolf-Defender L3 uses the public -small model. ONNX fp16 is expected under onnx/onnx_fp16.
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L3,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "config.json",
        destination_path: "l3/config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L3,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "tokenizer.json",
        destination_path: "l3/tokenizer.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L3,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "tokenizer_config.json",
        destination_path: "l3/tokenizer_config.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L3,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "special_tokens_map.json",
        destination_path: "l3/special_tokens_map.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::Injection,
        level: SecurityLevel::L3,
        repo: "patronus-studio/wolf-defender-prompt-injection-small",
        source_path: "onnx/onnx_fp16/model_fp16.onnx",
        destination_path: "l3/onnx/onnx_fp16/model_fp16.onnx",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L1,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "l1/l1_rules.json",
        destination_path: "prompts/l1_rules.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L2,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "l2/l2_config.json",
        destination_path: "prompts/l2_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L2,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "cascade/cascade_config.json",
        destination_path: "prompts/cascade_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "tokenizer.json",
        destination_path: "prompts/tokenizer.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "tokenizer_config.json",
        destination_path: "prompts/tokenizer_config.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "special_tokens_map.json",
        destination_path: "prompts/special_tokens_map.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "onnx/model_fp16.onnx",
        destination_path: "prompts/onnx/model_fp16.onnx",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "onnx/model.onnx",
        destination_path: "prompts/onnx/model.onnx",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-prompts-model",
        source_path: "onnx/model.onnx.data",
        destination_path: "prompts/onnx/model.onnx.data",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L1,
        repo: "patronus-studio/tool-executions-model",
        source_path: "l1/l1_rules.json",
        destination_path: "executions/l1_rules.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L2,
        repo: "patronus-studio/tool-executions-model",
        source_path: "l2/l2_config.json",
        destination_path: "executions/l2_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L2,
        repo: "patronus-studio/tool-executions-model",
        source_path: "cascade/cascade_config.json",
        destination_path: "executions/cascade_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-executions-model",
        source_path: "tokenizer.json",
        destination_path: "executions/tokenizer.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-executions-model",
        source_path: "tokenizer_config.json",
        destination_path: "executions/tokenizer_config.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-executions-model",
        source_path: "special_tokens_map.json",
        destination_path: "executions/special_tokens_map.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-executions-model",
        source_path: "onnx/model_fp16.onnx",
        destination_path: "executions/onnx/model_fp16.onnx",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-executions-model",
        source_path: "onnx/model.onnx",
        destination_path: "executions/onnx/model.onnx",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-executions-model",
        source_path: "onnx/model.onnx.data",
        destination_path: "executions/onnx/model.onnx.data",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L1,
        repo: "patronus-studio/tool-description-model",
        source_path: "l1/l1_rules.json",
        destination_path: "descriptions/l1_rules.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L2,
        repo: "patronus-studio/tool-description-model",
        source_path: "l2/l2_config.json",
        destination_path: "descriptions/l2_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L2,
        repo: "patronus-studio/tool-description-model",
        source_path: "cascade/cascade_config.json",
        destination_path: "descriptions/cascade_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-description-model",
        source_path: "tokenizer.json",
        destination_path: "descriptions/tokenizer.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-description-model",
        source_path: "tokenizer_config.json",
        destination_path: "descriptions/tokenizer_config.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-description-model",
        source_path: "special_tokens_map.json",
        destination_path: "descriptions/special_tokens_map.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-description-model",
        source_path: "onnx/model_fp16.onnx",
        destination_path: "descriptions/onnx/model_fp16.onnx",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-description-model",
        source_path: "onnx/model.onnx",
        destination_path: "descriptions/onnx/model.onnx",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::ToolClassifier,
        level: SecurityLevel::L3,
        repo: "patronus-studio/tool-description-model",
        source_path: "onnx/model.onnx.data",
        destination_path: "descriptions/onnx/model.onnx.data",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L1,
        repo: "patronus-studio/user-intent-model",
        source_path: "l1/l1_rules.json",
        destination_path: "prompts/l1_rules.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L2,
        repo: "patronus-studio/user-intent-model",
        source_path: "l2/l2_config.json",
        destination_path: "prompts/l2_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L2,
        repo: "patronus-studio/user-intent-model",
        source_path: "cascade/cascade_config.json",
        destination_path: "prompts/cascade_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L3,
        repo: "patronus-studio/user-intent-model",
        source_path: "tokenizer.json",
        destination_path: "prompts/tokenizer.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L3,
        repo: "patronus-studio/user-intent-model",
        source_path: "tokenizer_config.json",
        destination_path: "prompts/tokenizer_config.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L3,
        repo: "patronus-studio/user-intent-model",
        source_path: "special_tokens_map.json",
        destination_path: "prompts/special_tokens_map.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L3,
        repo: "patronus-studio/user-intent-model",
        source_path: "onnx/model_fp16.onnx",
        destination_path: "prompts/onnx/model_fp16.onnx",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L3,
        repo: "patronus-studio/user-intent-model",
        source_path: "onnx/model.onnx",
        destination_path: "prompts/onnx/model.onnx",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::UserIntent,
        level: SecurityLevel::L3,
        repo: "patronus-studio/user-intent-model",
        source_path: "onnx/model.onnx.data",
        destination_path: "prompts/onnx/model.onnx.data",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L1,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "l1/l1_rules.json",
        destination_path: "prompts/l1_rules.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L2,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "l2/l2_config.json",
        destination_path: "prompts/l2_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L2,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "cascade/cascade_config.json",
        destination_path: "prompts/cascade_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L3,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "tokenizer.json",
        destination_path: "prompts/tokenizer.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L3,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "tokenizer_config.json",
        destination_path: "prompts/tokenizer_config.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L3,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "special_tokens_map.json",
        destination_path: "prompts/special_tokens_map.json",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L3,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "onnx/onnx_fp16/model_fp16.onnx",
        destination_path: "prompts/onnx/model_fp16.onnx",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L3,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "onnx/model.onnx",
        destination_path: "prompts/onnx/model.onnx",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::SensitiveDocuments,
        level: SecurityLevel::L3,
        repo: "patronus-studio/orca-sonar-document-classifier",
        source_path: "onnx/model.onnx.data",
        destination_path: "prompts/onnx/model.onnx.data",
        required: false,
    },
    AssetSpec {
        category: SecurityCategory::Pii,
        level: SecurityLevel::L1,
        repo: "patronus-studio/pii-model",
        source_path: "l1/l1_rules.json",
        destination_path: "prompts/l1_rules.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Pii,
        level: SecurityLevel::L2,
        repo: "patronus-studio/pii-model",
        source_path: "l2/l2_config.json",
        destination_path: "prompts/l2_config.json",
        required: true,
    },
    AssetSpec {
        category: SecurityCategory::Pii,
        level: SecurityLevel::L2,
        repo: "patronus-studio/pii-model",
        source_path: "cascade/cascade_config.json",
        destination_path: "prompts/cascade_config.json",
        required: true,
    },
];
