#!/usr/bin/env bash
# Download the immutable Coordinator deployment assets and run them as root.
# The image workflow replaces the release markers below.
set -euo pipefail
set +x
umask 077

RELEASE_COMMIT='__RELEASE_COMMIT__'
COORDINATOR_IMAGE='__COORDINATOR_IMAGE__'
DEPLOY_DIR=/opt/patronus/ark-coordinator
STATE_DIR=/var/lib/patronus-coordinator
COORDINATOR_IP=
API_KEY_FILES=()
CUBE_KEY_FILE=
REDIS_URL_FILE=
CUBE_ORIGINS_FILE=

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
compose() { docker compose --project-directory "$DEPLOY_DIR" -f "$DEPLOY_DIR/compose.yaml" "$@"; }

validate_host() {
    [[ $EUID == 0 ]] || die 'Run with sudo/root.'
    python3 - "$COORDINATOR_IP" <<'PY' || die 'Coordinator IP must be a private IPv4 address.'
import ipaddress
import sys

address = ipaddress.ip_address(sys.argv[1])
if address.version != 4 or not address.is_private or address.is_loopback:
    raise SystemExit(1)
PY
    ip -4 -o address show | grep -Eq " $COORDINATOR_IP/[0-9]+ " || die 'Coordinator private IP is not configured on this host.'
    install -d -m 0700 "$STATE_DIR" "$DEPLOY_DIR"
}

install_docker() {
    if ! command -v docker >/dev/null; then
        # shellcheck disable=SC1091 -- file exists on supported Debian/Ubuntu hosts.
        . /etc/os-release
        [[ $ID == ubuntu && $VERSION_ID == 24.04 ]] || die 'Automatic Docker installation requires Ubuntu 24.04.'
        apt-get update
        apt-get install -y ca-certificates curl python3
        install -d -m 0755 /etc/apt/keyrings
        curl --fail --silent --show-error --proto '=https' --tlsv1.2 \
            https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod 0644 /etc/apt/keyrings/docker.asc
        cat > /etc/apt/sources.list.d/docker.sources <<'EOF'
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: noble
Components: stable
Architectures: amd64
Signed-By: /etc/apt/keyrings/docker.asc
EOF
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    fi
    command -v python3 >/dev/null || die 'python3 is required.'
    systemctl enable --now docker
    docker compose version
    local compose_version
    compose_version=$(docker compose version --short)
    [[ $compose_version =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+) ]] || die 'Cannot determine Docker Compose version.'
    (( BASH_REMATCH[1] > 2 || (BASH_REMATCH[1] == 2 && BASH_REMATCH[2] >= 20) )) || die 'Docker Compose 2.20 or newer is required.'
}

fetch_assets() {
    [[ $RELEASE_COMMIT =~ ^[0-9a-f]{40}$ ]] || die 'Use a bootstrap generated by Coordinator image CI.'
    [[ $COORDINATOR_IMAGE =~ ^ghcr\.io/patronus-protect/ark-coordinator@sha256:[0-9a-f]{64}$ ]] || die 'Coordinator image must be pinned to a GHCR digest.'
    local staging file
    staging=$(mktemp -d "$DEPLOY_DIR/.download.XXXXXX")
    for file in compose.yaml config.template.yaml render_config.py smoke.py; do
        curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' --tlsv1.2 \
            --connect-timeout 10 --max-time 120 \
            "https://raw.githubusercontent.com/patronus-protect/patronus-security/$RELEASE_COMMIT/ark-coordinator/deploy/$file" \
            -o "$staging/$file"
    done
    for file in compose.yaml config.template.yaml render_config.py smoke.py; do
        install -m 0600 "$staging/$file" "$DEPLOY_DIR/$file"
    done
    rm -r "$staging"
}

configure() {
    if (( ${#API_KEY_FILES[@]} == 0 )); then
        [[ -f $DEPLOY_DIR/config.yaml && -f $DEPLOY_DIR/cube.token && -f $DEPLOY_DIR/redis.url ]] || \
            die 'First deploy requires API, Cube and Redis secret files.'
        return
    fi
    [[ -n $CUBE_KEY_FILE && -n $REDIS_URL_FILE && -n $CUBE_ORIGINS_FILE ]] || \
        die 'Supply Cube, Redis and Cube-origin files together with API keys.'
    local args=() key
    for key in "${API_KEY_FILES[@]}"; do args+=(--api-key-file "$key"); done
    python3 "$DEPLOY_DIR/render_config.py" "$DEPLOY_DIR" "${args[@]}" \
        --cube-key-file "$CUBE_KEY_FILE" --redis-url-file "$REDIS_URL_FILE" \
        --cube-origins-file "$CUBE_ORIGINS_FILE"
}

stack_check() {
    compose ps
    local id
    id=$(compose ps -q coordinator)
    [[ -n $id ]] || die 'Coordinator container is missing.'
    docker inspect "$id" | python3 -c '
import json, sys
item = json.load(sys.stdin)[0]
host = item["HostConfig"]
assert item["State"]["Running"] and item["State"]["Health"]["Status"] == "healthy"
assert host["RestartPolicy"]["Name"] == "unless-stopped"
assert host["ReadonlyRootfs"] and host["Privileged"] is False
assert set((host.get("PortBindings") or {})) == {"8090/tcp"}
expected = {(sys.argv[1], "8090"), ("127.0.0.1", "8090")}
actual = {(item["HostIp"], item["HostPort"]) for item in host["PortBindings"]["8090/tcp"]}
assert actual == expected
' "$COORDINATOR_IP"
    python3 "$DEPLOY_DIR/smoke.py" --url http://127.0.0.1:8090
}

deploy() {
    install_docker
    fetch_assets
    configure
    docker pull "$COORDINATOR_IMAGE"
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.version"}}' "$COORDINATOR_IMAGE") == 0.1.6 ]] || die 'Expected Coordinator 0.1.6.'
    [[ $(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' "$COORDINATOR_IMAGE") == "$RELEASE_COMMIT" ]] || die 'Image/config revision mismatch.'
    printf 'COORDINATOR_IMAGE=%s\nCOORDINATOR_IP=%s\n' "$COORDINATOR_IMAGE" "$COORDINATOR_IP" > "$DEPLOY_DIR/.env"
    chmod 0600 "$DEPLOY_DIR/.env"
    compose config --quiet
    compose up -d --no-build --force-recreate --wait --wait-timeout 120
    stack_check
    if (( ${#API_KEY_FILES[@]} > 0 )); then
        python3 "$DEPLOY_DIR/smoke.py" --url http://127.0.0.1:8090 --key-file "${API_KEY_FILES[0]}"
    fi
    printf '%s\n' "$RELEASE_COMMIT" > "$STATE_DIR/deployed-commit"
    printf 'Coordinator deployment and private Cube scan passed. Configure DCD/ALB next.\n'
}

verify() {
    [[ -f $STATE_DIR/deployed-commit ]] || die 'Deploy first.'
    [[ $(cat "$STATE_DIR/deployed-commit") == "$RELEASE_COMMIT" ]] || die 'Bootstrap revision differs from deployed revision.'
    systemctl is-active --quiet docker
    stack_check
    printf 'Coordinator runtime verification passed.\n'
}

phase=${1:-help}
[[ $# == 0 ]] || shift
while [[ $# -gt 0 ]]; do
    case "$1" in
        --coordinator-ip|--api-key-file|--cube-key-file|--redis-url-file|--cube-origins-file)
            [[ $# -ge 2 && -n $2 ]] || die "Missing value for $1."
            case "$1" in
                --coordinator-ip) COORDINATOR_IP=$2 ;;
                --api-key-file) API_KEY_FILES+=("$2") ;;
                --cube-key-file) CUBE_KEY_FILE=$2 ;;
                --redis-url-file) REDIS_URL_FILE=$2 ;;
                --cube-origins-file) CUBE_ORIGINS_FILE=$2 ;;
            esac
            shift 2 ;;
        *) die "Unknown option: $1" ;;
    esac
done

case "$phase" in
    deploy) validate_host; deploy ;;
    verify) validate_host; verify ;;
    help|--help|-h) printf '%s\n' \
        'Usage: sudo bash bootstrap.sh deploy --coordinator-ip PRIVATE_IPV4 --api-key-file /root/origin.key --cube-key-file /root/cube.key --redis-url-file /root/redis.url --cube-origins-file /root/cube-origins.txt' \
        'Repeat --api-key-file during key rotation. Omit secret arguments on later unchanged deploys.' \
        'Input files must be root-owned, mode 0600 or stricter. Secret values are never printed.' \
        'Run verify with only --coordinator-ip after reboot or host maintenance.' ;;
    *) die 'Expected deploy or verify.' ;;
esac
